### PR TITLE
[Ivy 10] MARP-1249  Fix Demo can't start #27

### LINKED ISSUE #27: Demos do not work
Dear @ivy-sgi, we have found the following bug: 

**Describe the bug**

There are two business processes in the demo - both do not work in designer 10.0.23

**To Reproduce**
1. Go to approval-decision-utils-demo - Processes - Business Processes
2. Click on : either business process "login" or "ticketprocess"

**Expected behavior**
[A clear and concise description of what you expected to happen.
](https://market.axonivy.com/approval-decision-utils#tab-demo) - these UIs do not open

**Screenshots**

image
image

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win11

**Smartphone (please complete the following information):**

**Additional context**
Tested in designer 10.0.23

### PR DESCRIPTION
**Pull request by anh-bolt**
Fix #27

### CODE REVIEW

**Comment by nvvi** [comment]
LGTM

**Review by nvvi — APPROVED** [review]

File: approval-decision-utils/src_generated/com/axonivy/utils/approvaldecision/entities/BaseApprovalHistory_.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
+package com.axonivy.utils.approvaldecision.entities;
+
+import java.time.LocalDateTime;
+import javax.annotation.Generated;
+import javax.persistence.metamodel.SingularAttribute;
+import javax.persistence.metamodel.StaticMetamodel;
+
+@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
+@StaticMetamodel(BaseApprovalHistory.class)
+public abstract class BaseApprovalHistory_ extends com.axonivy.utils.persistence.beans.AuditableEntity_ {
```
Comment (ntqdinh-axonivy) [inline approval-decision-utils/src_generated/com/axonivy/utils/approvaldecision/entities/BaseApprovalHistory_.java:10]: I think this class can be generated when the project is build and need not to be included in our source code.

File: .github/workflows/dev.yml [hunk 2]
```diff
@@ -9,3 +9,7 @@ on:
 jobs:
   build:
     uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v4
+    with:
+        ivyVersion: 10.0.18
```
Comment (ntqdinh-axonivy) [inline .github/workflows/dev.yml:13]: could we leave it as 10 or 10-dev rather than fix version of 10.0.18/10.0.16

File: approval-decision-utils-product/README.md [hunk 3]
```diff
@@ -7,6 +7,7 @@ Axon Ivy's Approval Decision Utils provides a standardized approach for implemen
 - Provides a clear view of the ongoing approval history to meet regulatory, compliance, and transparency requirements.
 
 ## Demo
+The Demo shows how to integrate Approval-Decision-Utils in your project. It contains a simplest HSQLDB as datasource, that can be run without additional configuration.
```
Comment (ntqdinh-axonivy) [inline approval-decision-utils-product/README.md:10]: The demo shows how to integrate Approval-Decision-Utils _**into**_ your project. It includes a simple HSQLDB datasource that _**can run**_ without additional configuration.

Could you check grammar

File: approval-decision-utils-product/README.md [hunk 4]
```diff
@@ -26,56 +27,32 @@ Axon Ivy's Approval Decision Utils provides a standardized approach for implemen
...
-
-Example:
-
-    public class TicketRequest extends BaseRequest<ApprovalHistory>{}
-    public class ApprovalHistory extends BaseApprovalHistory{}
-
-### Integrate Approval decision to HTML dialog
-
-Example:
+The enum `ApprovalDecisionOption` to obtain decision options. If you prefer to use your own enum as options for decision, override the managed bean methods `getDecisionLabel(String decisionName)`, `List<Enum<?>> getDecisions()`.
```
Comment (ntqdinh-axonivy) [inline approval-decision-utils-product/README.md:53]: could you rework this sentences again? It make me so confused

**Review by ntqdinh-axonivy — CHANGES_REQUESTED** [review]

**Comment by ntqdinh-axonivy** [comment]
Btw, should we have the same PR for v12 ?

File: approval-decision-utils-product/README.md (hunk 4 above)
Comment (anh-bolt) [reply approval-decision-utils-product/README.md]: @ntqdinh-axonivy I update this block. Could you check it?

**Review by ntqdinh-axonivy — APPROVED** [review]
LGTM

**Comment by ntqdinh-axonivy** [comment]
HI @anh-bolt 
This PR look good. Please go ahead
